# Generated by Django 4.2.14 on 2024-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipeapi.RecipeIngredient', to='recipeapi.ingredient'),
        ),
    ]
